"""The "did a human type this" rules. Synthetic records only."""
import json

import pytest

from convo_chain import core as T
from convo_chain import looks_injected, typed_text

SID = "22222222-2222-4222-8222-222222222222"


def _user(content):
    return {"type": "user", "message": {"role": "user", "content": content}}


def test_a_plain_string_is_typed_text():
    assert typed_text(_user("  hello there  ")) == "hello there"


@pytest.mark.parametrize("content", [
    [{"type": "text", "text": "skill body injected as blocks"}],
    [{"type": "tool_result", "tool_use_id": "t1", "content": "ok"}],
    "", "   ", None, 42,
])
def test_block_lists_and_empty_strings_are_not_typed_text(content):
    assert typed_text(_user(content)) is None


@pytest.mark.parametrize("entry", [
    {"type": "user"}, {"type": "user", "message": None},
    {"type": "user", "message": "a string where an object belongs"},
    {"type": "user", "message": ["a", "list"]}, "not a dict",
])
def test_malformed_entries_answer_none_instead_of_raising(entry):
    assert typed_text(entry) is None


@pytest.mark.parametrize("text", [
    "<system-reminder>x</system-reminder>", "  <command-name>/x</command-name>",
    "<command-message>x", "<local-command-stdout>x", "Caveat: generated by a hook",
    "[Request interrupted by user]", "<task-notification>done</task-notification>",
])
def test_injected_prefixes_are_recognised(text):
    assert looks_injected(text) is True


@pytest.mark.parametrize("text", [
    "please run the tests", "what does <system-reminder> mean?", "caveat: lower case is typed",
])
def test_ordinary_text_is_not_injected(text):
    """Negative control: a rule that calls everything injected would pass the test above."""
    assert looks_injected(text) is False


def test_a_malformed_user_line_does_not_break_the_index(tmp_path):
    """One line whose `message` is a string used to raise inside indexing, taking the whole
    session down. It must count as a non-human line and leave the rest of the chain intact."""
    d = tmp_path / "proj-a"
    d.mkdir()
    u1 = "00000000-0000-4000-8000-000000000001"
    u2 = "00000000-0000-4000-8000-000000000002"
    rows = [
        {"type": "user", "uuid": u1, "parentUuid": None, "sessionId": SID,
         "message": {"role": "user", "content": "a real question"}},
        {"type": "user", "uuid": u2, "parentUuid": u1, "sessionId": SID, "message": "garbled"},
    ]
    (d / f"{SID}.jsonl").write_text("".join(json.dumps(r) + "\n" for r in rows), encoding="utf-8")
    T.clear_cache()
    r = T.chain(SID, root=str(tmp_path))
    kinds = [s["kind"] for t in r["turns"] for s in t.get("steps", [])]
    assert kinds == ["human", "usermeta"]
